### ISSUE TITLE
2.1.1 issue - ActionBar text is hidden 

### ISSUE THREAD

**Issue by skr1p7k1dd** [chrisjenx/Calligraphy#200]
I've been experiencing this crazy issue and I'm not quite sure whats causing it, but upgrading from 2.1.0 to 2.1.1 causes the action bar title text to disappear on almost all of my activities. My activities are themed with Base.Theme.AppCompat and extend ActionBarActivity. An odd thing I noticed is that in 2.1.1, the AppCompatActivity class does not exist and in 2.1.0, ActionBarActivity extends AppCompatActivity. That might possibly be related to the issue. Using 2.1.1, the only way I can get the action bar text to come back is by removing CalligraphyContextWrapper.

I know this might not be a whole lot to go off of, but maybe you can take it from here.

**Comment by chrisjenx** [comment]
Well 2.1.1 is WIP snapshot, so the way it handles the Toolbar text inflation is experimental.

`AppCompatActivity` and `ActionBarActivity` are part of the support library, really you should not be including any transitive dependences from Calligraphy. We don't use anything from the support library. (Apart from checking the classpath to see if they exist).

The only thing I would say, is drop `Toolbar` in for `Actionbar`. `Actionbar is actually backed by the `Toolbar`.

Also do *not* use the `Base.*` themes. Use `Theme.AppCompat.*`

Look at the Sample app: [styles.xml](https://github.com/chrisjenx/Calligraphy/blob/fix/force-toolbar-inflation/CalligraphySample/src/main/res/values/styles.xml)
And [activity.xml](https://github.com/chrisjenx/Calligraphy/blob/fix/force-toolbar-inflation/CalligraphySample/src/main/res/layout/activity_main.xml)

If you want to keep using what you have you will need to give a full example, otherwise I'm just guessing your implementation.

**Comment by chrisjenx** [comment]
Hey try the released 2.2.0, I tweaked the way we handle the Toolbar.
