### ISSUE TITLE
Fragment issue

### ISSUE THREAD

**Issue by ArthurSav** [chrisjenx/Calligraphy#29]
Hi, great library!
There's this issue where the calligraphy won't work. I have a nav drawer with a main activity(which includes the calligraphy) and 3 fragments attached to it for navigation.
The simple fragment will display my custom font correctly but the other two, which have listviews, won't display the font.
Any ideas?

**Comment by mychaelgo** [comment]
@c0nnector  do you implement getActivity().getLayoutInflater(); on a adapter?

**Comment by abhishekdepro** [comment]
Works like a charm.
Instead of `LayoutInflater mInflater = (LayoutInflater) getActivity().getLayoutInflater();`
use `LayoutInflater mInflater = getActivity().getLayoutInflater();` as (LayoutInflater) is redundant.
Finally:
`View convertView = mInflater.inflate(R.layout.fragment_home, null);
return convertView`
