### ISSUE TITLE
Items in navigation drawer don't have the custom font? 

### ISSUE THREAD

**Issue by RobbySmet** [chrisjenx/Calligraphy#78]
Hi,

This library works great but I have one problem, the navigation drawer items don't get the custom font I apply to them in xml. 

```
<TextView
    android:id="@+id/tv_title"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_centerVertical="true"
    android:layout_marginLeft="20dp"
    android:textColor="@android:color/white"
    android:textSize="18sp"
    fontPath="fonts/AvenirNextCondensed_Italic.ttf"
    tools:text="Nieuw" />
```

This is for example a navigation item xml layout. 
In my activity with the navigation drawer I add

```
@Override
protected void attachBaseContext(Context newBase) {
    super.attachBaseContext(new CalligraphyContextWrapper(newBase));
}
```

It does work in every other part of my app. Is this a known bug or am I doing something wrong ?

**Comment by bogdanRada** [comment]
@FlorentAnders , can you tell me what entry you made in the Application class? I seem to have same problem. Although i am not using an adapter, because they are static items, I apply a theme to the NavigationView, and a text appearance on items, however the items have the correct font only when unchecked, when they are checked, the font changes to Monospace :(
